"use client";

import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Container from "@/components/Container";
import { ThemeProvider } from "next-themes";
import Footer2 from "@/components/Footer2";
import ScrollTop from "@/components/ScrollTop";
 


// export const metadata = {
//   title: "valy-web",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    
      <html lang="en">
        <title>valy-web</title>
        <meta name="description" content="My Portfolio Website" />
          <body>
        <ThemeProvider attribute="class">
            <Header />
            <ScrollTop/>
    
            {children}
                
            <hr className="border-gray-800 w-full"/>
            <Container>
              <Footer2/>
            </Container>
        </ThemeProvider>
       
          </body>
      </html>
   
  );
}
